# main
verbose_main: false
main_iter_rate: 40
height: 2
look_ahead: 1
close_enough: 0.2
average_speed: 2.0

# motion
verbose_motion: true
use_ground_truth: true
qa: 0.0002
qx: 0.005
qy: 0.012
qz: 0.005
enable_gps: true
r_gps_x: 0.014522
r_gps_y: 0.004728
r_gps_z: 0.014374
enable_magnet: true
r_mgn_a: 0.00070
# range from 0.000-0.001 for now, 0.000 most common
enable_baro: true
r_bar_z: 0.01180
# currently ranges from 0.008-0.03, previously ranged from 0.015-0.024 for now
enable_sonar: true
r_snr_z: 0.00002
# range from 0.000-0.000 for now, 0.001 most common
motion_iter_rate: 20

# move
enable_move: true
verbose_move: true
Kp_lin: 1.1
Ki_lin: 0.05
Kd_lin: 0.6
Kp_z: 1.3
Ki_z: 0.05
Kd_z: 0.2
yaw_rate: 0.5
max_lin_vel: 2
max_z_vel: 0.5
move_iter_rate: 40

# run param used automatically and should not be written